package cu.tko.kbnco_metro.logica;

import java.util.Date;

/**
 * Created by a.guerra on 4/4/2018.
 */

public class Saldo {
    public Date fecha;
    public Double monto;
    public TIPO_MONEDA moneda;
    public boolean isAutoGenerated;

    @Override
    public String toString()
    {
        return this.monto.toString();
    }
}
